# -*- coding: utf-8 -*-
"""PlantProjWeatherStationData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t8wl0aqKKZm5Dy6BF6ABmIJrMn6WJqgf
"""

import requests
import pandas as pd

# https://openweathermap.org/api/one-call-3#history_daily_aggregation_how

def get_weather(lat, lon, api_key):
  # Can only make 10,000 calls per day, so be careful. I'm also not using historic.
    url = f"https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={api_key}"
    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        return data
    else:
        print("Error fetching data:", response.status_code)
        return None

def main(path, api_key):
    weather_station_storage= []

    df = pd.read_csv(path)
    lat = df["latitude"].tolist()
    lon = df["longitude"]

    for i in range(len(lat)):
      weather_data = get_weather(lat[i], lon[i], api_key)

      if weather_data:
          temp = weather_data['main']['temp']
          description = weather_data['weather'][0]['description']
          humidity = weather_data['main']['humidity']
          wind_speed = weather_data['wind']['speed'] #m/s
          weather_station_storage.append([temp,description,humidity,wind_speed])
      else:
          print("Failed to fetch weather data.")

    weather_station_df = pd.DataFrame(weather_station_storage, columns=["Temp", "Description", "Humidity", "Wind Speed"])
    df["Temperature"] = weather_station_df["Temp"]
    df["Description"] = weather_station_df["Description"]
    df["Humidity"] = weather_station_df["Humidity"]
    df["Wind Speed"] = weather_station_df["Wind Speed"]

    df.to_csv("exceptional_plants_LatLon_WeatherStation.csv")



